server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
#      defaultZone: http://172.17.0.2:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
